Repository Cognifide/aet, pull requests merged in 2018-08, with the labels that each got.

#298 [#214] Filtering accessibility errors by markup
  CHANGELOG.md
  core/jobs/src/main/java/com/cognifide/aet/job/common/datafilters/accessibilityfilter/AccessibilityFilter.java
  core/jobs/src/test/java/com/cognifide/aet/job/common/datafilters/accessibilityfilter/AccessibilityFilterTest.java
  documentation/src/main/wiki/AccessibilityDataFilter.md
  integration-tests/test-suite/partials/accessibility-filtered.xml
Labels: enhancement

#300 Added creating indexes for collection
  CHANGELOG.md
  core/datastorage/src/main/java/com/cognifide/aet/vs/mongodb/MongoDBClient.java
Labels: enhancement

#307 Troubleshooting AET - first version of a document
  documentation/src/main/DocumentationTemplate.md
  documentation/src/main/wiki/AetSuiteMigration.md
  documentation/src/main/wiki/Troubleshooting.md
  documentation/src/main/wiki/_Sidebar.md
Labels: wiki

#296 Validation if status codes comparators parameters were provided
  CHANGELOG.md
  core/jobs/src/main/java/com/cognifide/aet/job/common/comparators/statuscodes/StatusCodesComparator.java
  core/jobs/src/main/java/com/cognifide/aet/job/common/comparators/statuscodes/StatusCodesFilter.java
  core/jobs/src/test/java/com/cognifide/aet/job/common/comparators/statuscodes/StatusCodesComparatorTest.java
  core/jobs/src/test/java/com/cognifide/aet/job/common/comparators/statuscodes/StatusCodesFilterTest.java
  core/jobs/src/test/resources/mock/StatusCodesComparator/a-lot-of-errors-with-exclude-result.json
  core/jobs/src/test/resources/mock/StatusCodesComparator/default-range-399-601-errors-result.json
  core/jobs/src/test/resources/mock/StatusCodesComparator/default-range-400-600-errors-result.json
  core/jobs/src/test/resources/mock/StatusCodesComparator/not-existing-page-404-result.json
  documentation/src/main/wiki/StatusCodesComparator.md
  documentation/src/main/wiki/StatusCodesDataFilters.md
  integration-tests/sanity-functional/src/test/java/com/cognifide/aet/sanity/functional/HomePageTilesTest.java
  integration-tests/sanity-functional/src/test/resources/features/filtering.feature
  integration-tests/test-suite/partials/status-codes.xml
Labels: enhancement, wiki

#293 Newfeature/layout comparator with treshold
  CHANGELOG.md
  api/communication-api/src/main/java/com/cognifide/aet/communication/api/metadata/ComparatorStepResult.java
  core/jobs/src/main/java/com/cognifide/aet/job/common/comparators/layout/LayoutComparator.java
  core/jobs/src/main/java/com/cognifide/aet/job/common/comparators/layout/utils/ImageComparisonResult.java
  core/jobs/src/test/java/com/cognifide/aet/job/common/comparators/layout/LayoutComparatorTest.java
  core/jobs/src/test/java/com/cognifide/aet/job/common/comparators/layout/utils/ImageComparisonTest.java
  documentation/src/main/wiki/LayoutComparator.md
  documentation/src/main/wiki/SuiteReportFeatures.md
  documentation/src/main/wiki/SuiteReportLayoutCase.md
  documentation/src/main/wiki/assets/suiteReport/layout-conditionally-passed.PNG
  integration-tests/sanity-functional/src/main/java/com/cognifide/aet/sanity/functional/TestStatus.java
  integration-tests/sanity-functional/src/test/java/com/cognifide/aet/sanity/functional/HomePageTilesTest.java
  integration-tests/sanity-functional/src/test/resources/features/filtering.feature
  integration-tests/test-suite/partials/layout.xml
  report/src/main/webapp/app/app.module.js
  report/src/main/webapp/app/layout/main/suite/mainView.suite.view.html
  report/src/main/webapp/app/layout/main/test/mainView.test.view.html
  report/src/main/webapp/app/layout/main/url/reports/screen_layout.html
  report/src/main/webapp/app/layout/sidepanel/sidepanel.controller.js
  report/src/main/webapp/app/layout/sidepanel/sidepanel.view.html
  report/src/main/webapp/app/layout/toolbar/toolbarTop.view.html
  report/src/main/webapp/app/services/metadata.service.js
  report/src/main/webapp/assets/sass/_report.scss
  report/src/main/webapp/assets/sass/_sidebar.scss
  report/src/main/webapp/assets/sass/_test.scss
  report/src/main/webapp/assets/sass/_toolbar.scss
  report/src/main/webapp/assets/sass/_variables.scss
  report/src/main/webapp/assets/sass/main.scss
Labels: enhancement

#303 Feature/exclude
  CHANGELOG.md
  api/communication-api/src/main/java/com/cognifide/aet/communication/api/metadata/CollectorStepResult.java
  api/communication-api/src/main/java/com/cognifide/aet/communication/api/metadata/Payload.java
  api/communication-api/src/main/java/com/cognifide/aet/communication/api/metadata/StepResult.java
  api/communication-api/src/main/java/com/cognifide/aet/communication/api/metadata/exclude/ExcludedElement.java
  api/communication-api/src/main/java/com/cognifide/aet/communication/api/metadata/exclude/LayoutExclude.java
  api/jobs-api/src/main/java/com/cognifide/aet/job/api/comparator/ComparatorProperties.java
  core/jobs/src/main/java/com/cognifide/aet/job/common/collectors/screen/ScreenCollector.java
  core/jobs/src/main/java/com/cognifide/aet/job/common/comparators/layout/LayoutComparator.java
  core/jobs/src/main/java/com/cognifide/aet/job/common/comparators/layout/utils/ImageComparisonResult.java
  core/jobs/src/main/java/com/cognifide/aet/job/common/modifiers/WebElementsLocatorParams.java
  core/jobs/src/test/java/com/cognifide/aet/job/common/modifiers/login/LoginModifierTest.java
  core/worker/src/main/java/com/cognifide/aet/worker/listeners/ComparatorMessageListenerImpl.java
  documentation/src/main/wiki/ScreenCollector.md
  integration-tests/sample-site/src/main/webapp/sanity/comparators/layout/dynamic_content.jsp
  integration-tests/sanity-functional/src/test/java/com/cognifide/aet/sanity/functional/HomePageTilesTest.java
  integration-tests/sanity-functional/src/test/resources/features/filtering.feature
  integration-tests/test-suite/partials/layout.xml
  report/src/main/webapp/app/layout/main/url/reports/screen_layout.html
  report/src/main/webapp/assets/sass/_toolbar.scss
Labels: enhancement

#330 Changed brokerurl on url in default jms connection
  core/communication/src/main/java/com/cognifide/aet/queues/DefaultJmsConnection.java
  core/communication/src/main/java/com/cognifide/aet/queues/configuration/DefaultJmsConnectionConf.java
Labels: bug

#325 Support env variables in report manager
  CHANGELOG.md
  pom.xml
  rest-endpoint/pom.xml
  rest-endpoint/src/main/java/com/cognifide/aet/rest/helpers/ReportConfigurationManager.java
  rest-endpoint/src/main/java/com/cognifide/aet/rest/helpers/configuration/ReportConfigurationManagerConf.java
  rest-endpoint/src/test/java/com/cognifide/aet/rest/helpers/ReportConfigurationManagerTest.java
Labels: enhancement

#297 Advanced screen comparison feature
  report/src/main/webapp/app/app.config.js
  report/src/main/webapp/app/app.module.js
  report/src/main/webapp/app/components/compareScreens.directive.js
  report/src/main/webapp/app/layout/main/url/reports/screen_layout.html
  report/src/main/webapp/assets/sass/_newComparison.scss
  report/src/main/webapp/assets/sass/_test.scss
  report/src/main/webapp/assets/sass/_typography.scss
  report/src/main/webapp/assets/sass/_variables.scss
  report/src/main/webapp/assets/sass/main.scss
Labels: enhancement

#340 Wiki for Basic and Advanced env setup with Chrome and Grid
  documentation/src/main/DocumentationTemplate.md
  documentation/src/main/wiki/AETIn10Minutes.md
  documentation/src/main/wiki/AdvancedSetup.md
  documentation/src/main/wiki/BasicSetup.md
  documentation/src/main/wiki/LinuxAndWindowsSetup.md
  documentation/src/main/wiki/OsgiConfiguration.md
  documentation/src/main/wiki/SystemComponents.md
  documentation/src/main/wiki/_Sidebar.md
  documentation/src/main/wiki/assets/diagrams/aet-setup-advanced-grid-scaled.png
  documentation/src/main/wiki/assets/diagrams/aet-setup-with-vagrant.png
  vagrant/README.md
Labels: documentation, wiki

#301 New virtualization tool set (and new aet-cookbook version)
  .travis.yml
  CHANGELOG.md
  documentation/src/main/wiki/BasicSetup.md
  documentation/src/main/wiki/FAQ.md
  documentation/src/main/wiki/WhatsNew.md
  vagrant/Berksfile
  vagrant/Vagrantfile
  vagrant/metadata.rb
Labels: ToReveiw

#345 Deprecate AET maven plugin
  CHANGELOG.md
  client/README.md
  client/aet-maven-plugin/src/main/java/com/cognifide/aet/plugins/maven/RunTestSuiteMojo.java
  client/client-core/src/main/java/com/cognifide/aet/common/FatalErrorStatusProcessor.java
  client/client-core/src/main/java/com/cognifide/aet/common/JsonResponseHandler.java
  client/client-core/src/main/java/com/cognifide/aet/common/ProcessingErrorStatusProcessor.java
  client/client-core/src/main/java/com/cognifide/aet/common/ProcessorFactory.java
  client/client-core/src/main/java/com/cognifide/aet/common/ProgressStatusProcessor.java
  client/client-core/src/main/java/com/cognifide/aet/common/RedirectWriter.java
  client/client-core/src/main/java/com/cognifide/aet/common/ReportWriter.java
  client/client-core/src/main/java/com/cognifide/aet/common/RunnerTerminator.java
  client/client-core/src/main/java/com/cognifide/aet/common/StatusProcessor.java
  client/client-core/src/main/java/com/cognifide/aet/common/SuiteFinishedProcessor.java
  client/client-core/src/main/java/com/cognifide/aet/common/TestSuiteRunner.java
  client/client-core/src/main/java/com/cognifide/aet/common/UnexpectedStatusProcessor.java
  documentation/src/main/DocumentationTemplate.md
  documentation/src/main/wiki/ClientApplication.md
  documentation/src/main/wiki/TrackingProgress.md
  documentation/src/main/wiki/UpgradeNotes.md
  documentation/src/main/wiki/WebAPI.md
  documentation/src/main/wiki/_Sidebar.md
Labels: wiki
